#!/bin/sh
while /bin/true; do
  echo "Updating software from server."
  /usr/photon/bin/update_remote_sw
  echo "Starting remote display"
  su - display -c startx
  echo "Sleeping 30 seconds..."
  sleep 30
done
